name: blendingboardappfinalized
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+29

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  barcode_scan2: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  flutter_sfsymbols: ^1.0.0
  flutter_launcher_icons: "^0.7.0"
  qr_flutter: ^3.1.0
  auto_size_text: ^2.1.0
  permission_handler: ^10.0.0
  msix: ^0.1.19

flutter_icons:
  android: "blendingboardlogo"
  ios: false
  image_path: "assets/blendingBoardLogo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/blendingBoardLogo.png
    - assets/dyslexiaBrain.png
    - assets/water-blue-ocean.jpg
    - assets/backgroundRed.jpg
    - assets/backgroundYellow.jpg
    - assets/backgroundGreen.jpg
    - assets/backgroundPurple.jpg
    - assets/backgroundPink.jpg
    - assets/backgroundGrey.jpg
    - assets/winterBackground.jpg
    - assets/outlineDyslexiaBrainLogo.png
    - assets/outlineDyslexiaBrainLogoRed.png
    - assets/outlineDyslexiaBrainLogoBlue.png
    - assets/outlineDyslexiaBrainLogoYellow.png
    - assets/outlineDyslexiaBrainLogoGreen.png
    - assets/outlineDyslexiaBrainLogoPurple.png
    - assets/outlineDyslexiaBrainLogoPink.png
    - assets/outlineDyslexiaBrainLogoGray.png
    - assets/outlineDyslexiaBrainLogoTheme.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Black.ttf
          weight: 900
        - asset: fonts/SF-Pro-Rounded-Bold.ttf
          weight: 800
        - asset: fonts/SF-Pro-Rounded-Heavy.ttf
          weight: 700
        - asset: fonts/SF-Pro-Rounded-Light.ttf
          weight: 300
        - asset: fonts/SF-Pro-Rounded-Medium.ttf
          weight: 600
        - asset: fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: fonts/SF-Pro-Rounded-Semibold.ttf
          weight: 500
        - asset: fonts/SF-Pro-Rounded-Thin.ttf
          weight: 200
        - asset: fonts/SF-Pro-Rounded-Ultralight.ttf
          weight: 100
    - family: DidactGothic
      fonts:
        - asset: fonts/DidactGothic-Regular.ttf
          weight: 400
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: Blending Board
  publisher_display_name: N Leung
  identity_name: 4075NLeung.BlendingBoard
  publisher: CN=8280DB5D-E63C-4331-A0C4-1B4EB047BACC
  logo_path: C:\Users\debor\Downloads\NatalieCode\blendingboardfinalized\assets\blendingBoardLogo.png
  capabilities: "internetClient"
  msix_version: 1.0.3.0
  store: true